let n1=4;
let n2=5;
console.log(n1>n2);
console.log(n1<n2);
let a=2;
let b=2;
console.log(a==b);
let c=6;
let d="6";
console.log(c===d);
let g=6;
let h=5;
console.log(g!=h);  
let i="8";
let j=8;
console.log(i!==j);